export const homeObjOne = {
  id: "about",
  lightBg: true,
  lightText: true,
  lightTextDesc: false,
  topLine: "Website Apps",
  headLine: "Chatskuy Application",
  describtion: "A simple chatting website, users can chat with other users who have registered on this website..",
  buttonLabel: "Get Started",
  imgStart: true,
  image: require('../../images/mobil.png'),
  alt: "Image1",
  dark: true,
  primary: true,
  darkText: true,
};
export const homeObjTwo = {
  id: "discover",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Website Apps",
  headLine: "Chatskuy Application",
  describtion: "A simple chatting website, users can chat with other users who have registered on this website..",
  buttonLabel: "Get Started",
  imgStart: false,
  image: require("../../images/mobil.png"),
  alt: "Image1",
  dark: false,
  primary: true,
  darkText: false,
};
export const homeObjThree = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: "Website Apps",
  headLine: "Chatskuy Application",
  describtion: "A simple chatting website, users can chat with other users who have registered on this website..",
  buttonLabel: "Get Started",
  imgStart: true,
  image: require("../../images/mobil.png"),
  alt: "Image1",
  dark: true,
  primary: true,
  darkText: true,
};